datastore_mysql_import.settings:
  type: config_object
  label: 'Datastore Mysql Import settings'
  mapping:
    remove_empty_rows:
      type: boolean
      label: 'Remove empty rows from the datastore table'
    strict_mode_disabled:
      type: boolean
      label: 'Disable strict mode for MySQL import and table alter'
