dkan_js_frontend.config:
  type: config_object
  mapping:
    css_folder:
      type: string
      label: 'CSS Directory'
    js_folder:
      type: string
      label: 'JS Directory'
    minified:
      type: boolean
      label: 'Is minified'
    preprocess:
      type: boolean
      label: 'Preprocess'
    datastore_query_api:
      type: boolean
      label: 'Datastore Query API Source'
    routes:
      type: sequence
      label: 'Routes'
      sequence:
        type: label
    js:
      type: mapping
      label: 'js'
      mapping:
        attributes:
          type: sequence
          label: 'Attributes'
          sequence:
            type: label
